name: hello-world-docker
on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world docker build
        run: docker build -t test-image .
      - name: Hello world docker run
        run: docker run test-image "Mona the Octocat"
        id: hello
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"